python main_ce.py --config ./config/nturgbd-cross-view/tmp/dynamic_mutual_ce_01_train_joint_mutual.yaml
python main_ce.py --config ./config/nturgbd-cross-view/tmp/dynamic_mutual_ce_03_train_joint_mutual.yaml
python main_ce.py --config ./config/nturgbd-cross-view/tmp/dynamic_mutual_ce_05_train_joint_mutual.yaml
python main_total.py --config ./config/nturgbd-cross-view/tmp/dynamic_mutual_total_01_train_joint_mutual.yaml
python main_total.py --config ./config/nturgbd-cross-view/tmp/dynamic_mutual_total_03_train_joint_mutual.yaml
python main_total.py --config ./config/nturgbd-cross-view/tmp/dynamic_mutual_total_05_train_joint_mutual.yaml
python main_ce.py --config ./config/nturgbd-cross-subject/tmp/dynamic_mutual_ce_01_train_joint_mutual.yaml
python main_cepy --config ./config/nturgbd-cross-subject/tmp/dynamic_mutual_ce_03_train_joint_mutual.yaml
python main_ce.py --config ./config/nturgbd-cross-subject/tmp/dynamic_mutual_ce_05_train_joint_mutual.yaml
python main_total.py --config ./config/nturgbd-cross-subject/tmp/dynamic_mutual_total_01_train_joint_mutual.yaml
python main_total.py --config ./config/nturgbd-cross-subject/tmp/dynamic_mutual_total_03_train_joint_mutual.yaml
python main_total.py --config ./config/nturgbd-cross-subject/tmp/dynamic_mutual_total_05_train_joint_mutual.yaml
